eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8082

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/vsbm
        registration:
          spring-with-test-scope:
            authorization-grant-type: authorization_code
            client-id: spring-demo
            client-secret: gdgDiOp11yQShNCsNkpSCBeoZzd07XP9
            provider: keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/vsbm/protocol/openid-connect/certs
