info:
  app:
    name: Gateway Server
    description: Gateway Server Application
    version: 1.0.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka/
  instance.prefer-ip-address: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/awbd
        registration:
          spring-with-test-scope:
            authorization-grant-type: authorization_code
            client-id: spring-demo
            client-secret: 48Rr7HruC57iZ5NsZRzt0rhqpHPdFPA5
            provider: keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/awbd/protocol/openid-connect/certs

server:
  port: 8071
